version: '2.1'
services:
  plex:
    #image: linuxserver/plex:bionic
    image: linuxserver/plex
    #image: ghcr.io/linuxserver/plex:bionic-1.23.1.4571-6119e8eed-ls32
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      #- UMASK_SET=022 #optional
    volumes:
      #- ./volumes/plex/config:/config
      - ~/Docker/PlexMetaData/config:/config
      #- ~/mnt/HDD/tvseries:/tv
      - /mnt/Plex/Entertainment:/media
      #- /media/miniCloud/Entertainment/MobiesBulk:/movies
      #- ~/mnt/HDD/movies:/movies
      - ./volumes/plex/transcode:/transcode
    restart: always
